### ISSUE TITLE
Train_model.py namespace error

### ISSUE THREAD

**Issue by lesliepy99** [mariob6/style_text#24]
Hello. I'm running the code as indicated, however when I run train_yelp.sh, an error appears as follows:
`Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/content/drive/My Drive/style_text/scripts/train_model.py", line 40, in <module>
    params = loadParams(args.machine)
AttributeError: 'Namespace' object has no attribute 'machine'`

I checked the code of train_model and found that the attribute "machine" doesn't make any sense.
`if __name__ == "__main__":
    logging.basicConfig(level=logging.DEBUG)
    parser = argparse.ArgumentParser()
    parser.add_argument("--train_file_style1", type=str)
    parser.add_argument("--train_file_style2", type=str)
    parser.add_argument("--evaluation_file_style1", type=str)
    parser.add_argument("--evaluation_file_style2", type=str)
    parser.add_argument("--vocabulary", type=str)
    parser.add_argument("--savefile", type=str)
    parser.add_argument("--logdir", type=str, default="")
    args = parser.parse_args()

    params = loadParams(args.machine)`

I'm a newbie to python and ML and would you please help me out?
THX!

**Comment by namespacegit** [comment]
> Hello. I'm running the code as indicated, however when I run train_yelp.sh, an error appears as follows:
> `Traceback (most recent call last): File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main "__main__", mod_spec) File "/usr/lib/python3.6/runpy.py", line 85, in _run_code exec(code, run_globals) File "/content/drive/My Drive/style_text/scripts/train_model.py", line 40, in <module> params = loadParams(args.machine) AttributeError: 'Namespace' object has no attribute 'machine'`
> 
> I checked the code of train_model and found that the attribute "machine" doesn't make any sense.
> `if **name** == "**main**":
> logging.basicConfig(level=logging.DEBUG)
> parser = argparse.ArgumentParser()
> parser.add_argument("--train_file_style1", type=str)
> parser.add_argument("--train_file_style2", type=str)
> parser.add_argument("--evaluation_file_style1", type=str)
> parser.add_argument("--evaluation_file_style2", type=str)
> parser.add_argument("--vocabulary", type=str)
> parser.add_argument("--savefile", type=str)
> parser.add_argument("--logdir", type=str, default="")
> args = parser.parse_args()
> 
> ```
> params = loadParams(args.machine)`
> ```
> 
> I'm a newbie to python and ML and would you please help me out?
> THX!

Just delete "args.machine" is OK.
